### ISSUE TITLE
No identifiers.timestamp attribute in PresentProof response (revocable cred) set from findy agent

### ISSUE THREAD

**Issue by tbruecke** [findy-network/findy-agent#319]
When I confirm a present-proof request, which requests attributes from one non-revocable and one revocable credential, I get the following [identifiers object](https://github.com/findy-network/findy-wrapper-go/blob/575dd0bbb46397519207d07d5d797cfeee804f41/anoncreds/anoncreds.go#L126) in PresentProofResponse body:
`"identifiers": [
{"schema_id": "FnhYpbRquQe6TaECgdYxY5:2:BAMF-Basis-ID:1.1", "cred_def_id": "FnhYpbRquQe6TaECgdYxY5:3:CL:12:default"}, {"schema_id": "FnhYpbRquQe6TaECgdYxY5:2:guest:1.0", "cred_def_id": "FnhYpbRquQe6TaECgdYxY5:3:CL:17:ssi-am-guest-local-abc001", "rev_reg_id": "FnhYpbRquQe6TaECgdYxY5:4:FnhYpbRquQe6TaECgdYxY5:3:CL:17:ssi-am-guest-local-abc001:CL_ACCUM:1bd976eb-5fc2-417e-8e5e-c711479d3119"}]}`
Normally there should be a "timestamp" field for the revocable credential (which is later important for verifier agent - see [aries rfc 0441](https://github.com/sklump/aries-rfcs/tree/master/concepts/0441-present-proof-best-practices#missing-timestamp)). This timestamp field is defined [here](https://github.com/findy-network/findy-wrapper-go/blob/575dd0bbb46397519207d07d5d797cfeee804f41/anoncreds/anoncreds.go#L126), but later seeming not set.

I also can't find the place in the code where this timestamp attribute is set in identifiers object. Is it possible that this variant is not fully implemented yet or am I missing something?

Regards

**Comment by lainio** [comment]
Thank you for the feedback! Highly appreciated.

Without checking the code, I can say that you are correct: 'this variant is not fully implemented.' During the early stages of the `findy-agent` development, we decided not to support revocation because the design AnonCreds 1.0 had many problems. We found no real-world use cases for **public** revocation in our business field. But never say never.

We'll study this case and offer a patch if it is easy to fix.
